# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-staging.yml
#
#
# URL of static site
url: "https://www.devicetree.org"
# Destination folder
destination: production.devicetree.org
# Production boolean used in layouts / includes
production: true
